### PR TITLE
Kernel build fixes

### PR DESCRIPTION
**Pull request by bw35**
Building the kernel from the linux_media repository w/o media_build requires some small modifications to the saa716x Kconfig and Makefile.

### CODE REVIEW

**Comment by tkurbad** [comment]
@bw35 These changes prevent the saa716x_budget module from being build w/ media_build.
How can this be overcome? Has media_build to be changed somehow?

**Comment by bw35** [comment]
@tkurbad In fact I didn't try with media_build. I've cross compiled the kernel in this repo. I'll try with media_build to see where it fails.

Maybe you have more info for me: For which kernel version did you try to build the drivers and what was the relevant output of the build process?

**Comment by tkurbad** [comment]
I tried to compile for kernel version 4.5.0. There weren't any build errors. Only after installing I noticed that the saa716x_budget module was missing (saa716x_core, saa716x_ff, and saa716x_hybrid were there, nonetheless)

I then checked out c9626a9e5e90cc9eac7d985159f0d67a6870146b and reran the build. Now the missing module is there again.

HTH,
Torsten

**Comment by bw35** [comment]
@tkurbad 
I can't reproduce your problem. I've done the media_build method as described in the [wiki](https://github.com/ljalves/linux_media/wiki/Installating) and got all modules including saa716x_budget.ko in the media_build/v4l directory. Checked with Kernel 4.1.15 and 4.5.0, latter required a small fix in the cdx2820r_core.c because of a change introduced by kernel 4.5 in include/linux/gpio/driver.

**Comment by tkurbad** [comment]
@bw35 
Strange. I'll look into it again after my next kernel update.

**Pull request merged**
